/* libAccessibility.h generated by valac 0.26.1, the Vala compiler, do not modify */


#ifndef __LIBACCESSIBILITY_H__
#define __LIBACCESSIBILITY_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define ACCESSIBILITY_TYPE_IACCESSIBLE (accessibility_iaccessible_get_type ())
#define ACCESSIBILITY_IACCESSIBLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ACCESSIBILITY_TYPE_IACCESSIBLE, AccessibilityIAccessible))
#define ACCESSIBILITY_IS_IACCESSIBLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ACCESSIBILITY_TYPE_IACCESSIBLE))
#define ACCESSIBILITY_IACCESSIBLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ACCESSIBILITY_TYPE_IACCESSIBLE, AccessibilityIAccessibleIface))

typedef struct _AccessibilityIAccessible AccessibilityIAccessible;
typedef struct _AccessibilityIAccessibleIface AccessibilityIAccessibleIface;

struct _AccessibilityIAccessibleIface {
	GTypeInterface parent_iface;
	void (*accDoDefaultAction) (AccessibilityIAccessible* self, GObject* childID);
	GObject* (*accHitTest) (AccessibilityIAccessible* self, gint xLeft, gint yTop);
	void (*accLocation) (AccessibilityIAccessible* self, gint* pxLeft, gint* pyTop, gint* pcxWidth, gint* pcyHeight, GObject* childID);
	GObject* (*accNavigate) (AccessibilityIAccessible* self, gint navDir, GObject* childID);
	void (*accSelect) (AccessibilityIAccessible* self, gint flagsSelect, GObject* childID);
	GObject* (*get_accChild) (AccessibilityIAccessible* self, GObject* childID);
	gchar* (*get_accDefaultAction) (AccessibilityIAccessible* self, GObject* childID);
	gchar* (*get_accDescription) (AccessibilityIAccessible* self, GObject* childID);
	gchar* (*get_accHelp) (AccessibilityIAccessible* self, GObject* childID);
	gint (*get_accHelpTopic) (AccessibilityIAccessible* self, gchar** pszHelpFile, GObject* childID);
	gchar* (*get_accKeyboardShortcut) (AccessibilityIAccessible* self, GObject* childID);
	gchar* (*get_accName) (AccessibilityIAccessible* self, GObject* childID);
	GObject* (*get_accRole) (AccessibilityIAccessible* self, GObject* childID);
	GObject* (*get_accState) (AccessibilityIAccessible* self, GObject* childID);
	gchar* (*get_accValue) (AccessibilityIAccessible* self, GObject* childID);
	void (*set_accName) (AccessibilityIAccessible* self, GObject* childID, const gchar* newName);
	void (*set_accValue) (AccessibilityIAccessible* self, GObject* childID, const gchar* newValue);
	gint (*get_accChildCount) (AccessibilityIAccessible* self);
	GObject* (*get_accFocus) (AccessibilityIAccessible* self);
	GObject* (*get_accParent) (AccessibilityIAccessible* self);
	GObject* (*get_accSelection) (AccessibilityIAccessible* self);
};


GType accessibility_iaccessible_get_type (void) G_GNUC_CONST;
void accessibility_iaccessible_accDoDefaultAction (AccessibilityIAccessible* self, GObject* childID);
GObject* accessibility_iaccessible_accHitTest (AccessibilityIAccessible* self, gint xLeft, gint yTop);
void accessibility_iaccessible_accLocation (AccessibilityIAccessible* self, gint* pxLeft, gint* pyTop, gint* pcxWidth, gint* pcyHeight, GObject* childID);
GObject* accessibility_iaccessible_accNavigate (AccessibilityIAccessible* self, gint navDir, GObject* childID);
void accessibility_iaccessible_accSelect (AccessibilityIAccessible* self, gint flagsSelect, GObject* childID);
GObject* accessibility_iaccessible_get_accChild (AccessibilityIAccessible* self, GObject* childID);
gchar* accessibility_iaccessible_get_accDefaultAction (AccessibilityIAccessible* self, GObject* childID);
gchar* accessibility_iaccessible_get_accDescription (AccessibilityIAccessible* self, GObject* childID);
gchar* accessibility_iaccessible_get_accHelp (AccessibilityIAccessible* self, GObject* childID);
gint accessibility_iaccessible_get_accHelpTopic (AccessibilityIAccessible* self, gchar** pszHelpFile, GObject* childID);
gchar* accessibility_iaccessible_get_accKeyboardShortcut (AccessibilityIAccessible* self, GObject* childID);
gchar* accessibility_iaccessible_get_accName (AccessibilityIAccessible* self, GObject* childID);
GObject* accessibility_iaccessible_get_accRole (AccessibilityIAccessible* self, GObject* childID);
GObject* accessibility_iaccessible_get_accState (AccessibilityIAccessible* self, GObject* childID);
gchar* accessibility_iaccessible_get_accValue (AccessibilityIAccessible* self, GObject* childID);
void accessibility_iaccessible_set_accName (AccessibilityIAccessible* self, GObject* childID, const gchar* newName);
void accessibility_iaccessible_set_accValue (AccessibilityIAccessible* self, GObject* childID, const gchar* newValue);
gint accessibility_iaccessible_get_accChildCount (AccessibilityIAccessible* self);
GObject* accessibility_iaccessible_get_accFocus (AccessibilityIAccessible* self);
GObject* accessibility_iaccessible_get_accParent (AccessibilityIAccessible* self);
GObject* accessibility_iaccessible_get_accSelection (AccessibilityIAccessible* self);


G_END_DECLS

#endif
