/* String.c generated by valac 0.26.1, the Vala compiler
 * generated from String.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define SYSTEM_TYPE_STRING (system_string_get_type ())
#define SYSTEM_STRING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TYPE_STRING, SystemString))
#define SYSTEM_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TYPE_STRING, SystemStringClass))
#define SYSTEM_IS_STRING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TYPE_STRING))
#define SYSTEM_IS_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TYPE_STRING))
#define SYSTEM_STRING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TYPE_STRING, SystemStringClass))

typedef struct _SystemString SystemString;
typedef struct _SystemStringClass SystemStringClass;
typedef struct _SystemStringPrivate SystemStringPrivate;
typedef struct _SystemParamSpecString SystemParamSpecString;

struct _SystemString {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SystemStringPrivate * priv;
};

struct _SystemStringClass {
	GTypeClass parent_class;
	void (*finalize) (SystemString *self);
};

struct _SystemParamSpecString {
	GParamSpec parent_instance;
};


static gpointer system_string_parent_class = NULL;

gpointer system_string_ref (gpointer instance);
void system_string_unref (gpointer instance);
GParamSpec* system_param_spec_string (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_value_set_string (GValue* value, gpointer v_object);
void system_value_take_string (GValue* value, gpointer v_object);
gpointer system_value_get_string (const GValue* value);
GType system_string_get_type (void) G_GNUC_CONST;
enum  {
	SYSTEM_STRING_DUMMY_PROPERTY
};
SystemString* system_string_new (void);
SystemString* system_string_construct (GType object_type);
static void system_string_finalize (SystemString* obj);


SystemString* system_string_construct (GType object_type) {
	SystemString* self = NULL;
	self = (SystemString*) g_type_create_instance (object_type);
	return self;
}


SystemString* system_string_new (void) {
	return system_string_construct (SYSTEM_TYPE_STRING);
}


static void system_value_string_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void system_value_string_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		system_string_unref (value->data[0].v_pointer);
	}
}


static void system_value_string_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = system_string_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer system_value_string_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* system_value_string_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SystemString* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = system_string_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* system_value_string_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SystemString** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = system_string_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* system_param_spec_string (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SystemParamSpecString* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SYSTEM_TYPE_STRING), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer system_value_get_string (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYSTEM_TYPE_STRING), NULL);
	return value->data[0].v_pointer;
}


void system_value_set_string (GValue* value, gpointer v_object) {
	SystemString* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYSTEM_TYPE_STRING));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYSTEM_TYPE_STRING));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		system_string_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		system_string_unref (old);
	}
}


void system_value_take_string (GValue* value, gpointer v_object) {
	SystemString* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYSTEM_TYPE_STRING));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYSTEM_TYPE_STRING));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		system_string_unref (old);
	}
}


static void system_string_class_init (SystemStringClass * klass) {
	system_string_parent_class = g_type_class_peek_parent (klass);
	((SystemStringClass *) klass)->finalize = system_string_finalize;
}


static void system_string_instance_init (SystemString * self) {
	self->ref_count = 1;
}


static void system_string_finalize (SystemString* obj) {
	SystemString * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_TYPE_STRING, SystemString);
	g_signal_handlers_destroy (self);
}


GType system_string_get_type (void) {
	static volatile gsize system_string_type_id__volatile = 0;
	if (g_once_init_enter (&system_string_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { system_value_string_init, system_value_string_free_value, system_value_string_copy_value, system_value_string_peek_pointer, "p", system_value_string_collect_value, "p", system_value_string_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SystemStringClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_string_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemString), 0, (GInstanceInitFunc) system_string_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType system_string_type_id;
		system_string_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SystemString", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&system_string_type_id__volatile, system_string_type_id);
	}
	return system_string_type_id__volatile;
}


gpointer system_string_ref (gpointer instance) {
	SystemString* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void system_string_unref (gpointer instance) {
	SystemString* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYSTEM_STRING_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



