/* String.h generated by valac 0.26.1, the Vala compiler, do not modify */


#ifndef __STRING_H__
#define __STRING_H__

#include <glib.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define SYSTEM_TYPE_STRING (system_string_get_type ())
#define SYSTEM_STRING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TYPE_STRING, SystemString))
#define SYSTEM_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TYPE_STRING, SystemStringClass))
#define SYSTEM_IS_STRING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TYPE_STRING))
#define SYSTEM_IS_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TYPE_STRING))
#define SYSTEM_STRING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TYPE_STRING, SystemStringClass))

typedef struct _SystemString SystemString;
typedef struct _SystemStringClass SystemStringClass;
typedef struct _SystemStringPrivate SystemStringPrivate;

struct _SystemString {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SystemStringPrivate * priv;
};

struct _SystemStringClass {
	GTypeClass parent_class;
	void (*finalize) (SystemString *self);
};


gpointer system_string_ref (gpointer instance);
void system_string_unref (gpointer instance);
GParamSpec* system_param_spec_string (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_value_set_string (GValue* value, gpointer v_object);
void system_value_take_string (GValue* value, gpointer v_object);
gpointer system_value_get_string (const GValue* value);
GType system_string_get_type (void) G_GNUC_CONST;
SystemString* system_string_new (void);
SystemString* system_string_construct (GType object_type);


G_END_DECLS

#endif
