/* String.vapi generated by valac 0.26.1, do not modify. */

namespace System {
	[CCode (cheader_filename = "String.h")]
	public class String : GLib.Object {
		public String ();
		public bool EndsWith (string string);
	}
}
